apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: formacion
  labels:
    app: mysql
spec:
  ports:
    - name: 3306-tcp
      protocol: TCP
      port: 3306
      targetPort: 3306
    - name: 33060-tcp
      protocol: TCP
      port: 33060
      targetPort: 33060
  selector:
    deploymentconfig: mysql
  type: ClusterIP
